name: Release Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Archive
        run:  |
          sudo zip -r KSU-Hexnode.zip *  
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: module
          path: KSU-Hexnode.zip
          retention-days: 5
